apply:
	terraform apply $(args)

check:
	terraform fmt
	terraform validate
	terraform plan

plan:
	terraform plan

destroy:
	terraform destroy $(args)

init:
	terraform init

refresh:
	terraform refresh

output:
	terraform output
